apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bbbtickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbbtickets
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bbbtickets
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - image: gcr.io/main-219410/ticket-booth-api:latest
        imagePullPolicy: Always
        name: bbbtickets
        env:
        - name: MYSQL_HOST
          value: 10.58.0.3
        - name: MYSQL_DATABASE
          value: bbb_prod
        - name: MYSQL_USER
          value: bbb_prod
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: bbbtickets
              key: mysqlPassword
        - name: MYSQL_PORT
          value: "3306"
        - name: PP_ID
          valueFrom:
            secretKeyRef:
              name: bbbtickets
              key: ppId
        - name: PP_SECRET
          valueFrom:
            secretKeyRef:
              name: bbbtickets
              key: ppSecret
        - name: API_SECRET
          valueFrom:
            secretKeyRef:
              name: bbbtickets
              key: apiSecret
        - name: SENDGRID_KEY
          valueFrom:
            secretKeyRef:
              name: bbbtickets
              key: sendgridKey
        - name: NODE_ENV
          value: production
        ports:
        - containerPort: 8081
          name: web
          protocol: TCP
        resources:
          requests:
            cpu: 10m

