apiVersion: v1
kind: Service
metadata:
  labels:
    app: bbbtickets
  name: bbbtickets
spec:
  selector:
    app: bbbtickets
  ports:
  - port: 8081
    protocol: TCP
  type: ClusterIP
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: bbbtickets
spec:
  host: api.bigbikebash.org.uk
  service: bbbtickets:8081
  prefix: /
