---
name: CI
on:
  push:
    branches:
      - master

jobs:
  build-docker:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }} 
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: |
          europe-west1-docker.pkg.dev/bigbikebash/docker/ticket-booth:latest
          europe-west1-docker.pkg.dev/bigbikebash/docker/ticket-booth:${{ github.sha }}
          europe-west1-docker.pkg.dev/bigbikebash/docker/ticket-booth:${{ github.ref_name }}
