---
name: CI
on:
  push:
    branches:
      - master

jobs:
  build-docker:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        tags: |
          ghcr.io/strideynet/ticket-booth:latest
          ghcr.io/strideynet/ticket-booth:${{ github.sha }}
          ghcr.io/strideynet/ticket-booth:${{ github.ref_name }}
